-- Customer Lifetime Value (CLV) Model
--
-- Definition: Average revenue generated by a customer throughout their entire relationship with the company.
-- Formula: CLV = SUM(bil_invoices.total_amount) / COUNT(DISTINCT crm_customers.customer_id)

with invoices as (
    select
        customer_id,
        total_amount
    from {{ ref('bil_invoices') }}
),

customers as (
    select
        customer_id
    from {{ ref('crm_customers') }}
)

select
    sum(i.total_amount) / count(distinct c.customer_id) as customer_lifetime_value
from invoices i
join customers c on c.customer_id = i.customer_id
;
