-- Customer Lifetime Value (CLV) Model
--
-- Definition: Average revenue generated by a customer throughout their entire relationship with the company.
-- Formula: CLV = Average monthly revenue × Average customer lifespan

with customer_data as (
    select
        c.customer_id,
        c.created_at,
        current_date() as current_date,
        datediff('month', c.created_at, current_date()) as customer_age_months,
        sum(i.total_amount) as total_revenue
    from {{ source('Combined Source', 'crm_customers') }} as c
    left join {{ source('Combined Source', 'bil_invoices') }} as i
        on c.customer_id = i.customer_id
    group by 1, 2, 3
),

lifetime_calculations as (
    select
        customer_id,
        customer_age_months,
        total_revenue,
        case
            when customer_age_months = 0 then 0
            when total_revenue = 0 then 0
            else
                -- Simple projection: if customer has been active for X months and 
                -- generated Y revenue, project this over expected lifespan (24 months as example)
                (total_revenue / customer_age_months) * 24
        end as lifetime_value
    from customer_data
    where customer_age_months > 0
)

select
    customer_id,
    lifetime_value,
    total_revenue,
    customer_age_months
from lifetime_calculations
