{{ config(materialized='view') }}

SELECT
    "CONTACT_ID"::INTEGER AS CONTACT_ID,
    "CUSTOMER_ID"::INTEGER AS CUSTOMER_ID,
    "CONTACT_TYPE"::VARCHAR AS CONTACT_TYPE,
    "CONTACT_VALUE"::VARCHAR AS CONTACT_VALUE,
    "IS_PRIMARY"::BOOLEAN AS IS_PRIMARY,
    "CONTACT_LABEL"::VARCHAR AS CONTACT_LABEL,
    "NOTE"::VARCHAR AS NOTE,
    "CREATED_AT"::VARCHAR AS CREATED_AT, -- Kept as VARCHAR per DBML
    "UPDATED_AT"::VARCHAR AS UPDATED_AT  -- Kept as VARCHAR per DBML
FROM {{ source('raw', 'CRM_CONTACTS') }}