version: 2
sources:
-   name: raw
    database: NOVACOM
    schema: BRONZE
    tables:
    -   name: users
        columns:
        -   name: id
        -   name: username
        -   name: email
        -   name: created_at
    -   name: orders
        columns:
        -   name: id
        -   name: user_id
        -   name: status
        -   name: created_at
    -   name: products
        columns:
        -   name: id
        -   name: name
        -   name: price
        -   name: created_at
