version: 2
sources:
    name: raw
    tables:
    -   name: crm_opportunities
        columns:
        -   name: opportunity_id
        -   name: stage
        -   name: assigned_sales_rep
        -   name: note
        -   name: updated_at
        -   name: pipeline_stage
        -   name: amount
        -   name: next_step
        -   name: account_id
        -   name: probability_of_close
        -   name: close_date
        -   name: created_at
    -   name: nwk_outages
        columns:
        -   name: impacted_customers_count
        -   name: outage_id
        -   name: assignment_id
        -   name: end_time
        -   name: start_time
        -   name: resolution
        -   name: updated_at
        -   name: cause
        -   name: created_at
        -   name: outage_type
        -   name: region
    -   name: crm_customers
        columns:
        -   name: start_date
        -   name: middle_name
        -   name: email
        -   name: address_line1
        -   name: city
        -   name: zip_code
        -   name: customer_segment
        -   name: created_at
        -   name: updated_at
        -   name: note
        -   name: status
        -   name: customer_tier
        -   name: country
        -   name: state
        -   name: address_line2
        -   name: date_of_birth
        -   name: phone
        -   name: last_name
        -   name: first_name
        -   name: customer_id
    -   name: sup_tickets
        columns:
        -   name: priority
        -   name: subject
        -   name: description
        -   name: channel_of_contact
        -   name: assigned_agent
        -   name: resolution_date
        -   name: updated_at
        -   name: created_at
        -   name: customer_id
        -   name: ticket_id
        -   name: created_date
        -   name: status
    -   name: crm_accounts
        columns:
        -   name: shipping_address
        -   name: billing_address
        -   name: status
        -   name: account_type
        -   name: customer_id
        -   name: note
        -   name: created_at
        -   name: updated_at
        -   name: account_balance
        -   name: currency_code
        -   name: creation_date
        -   name: account_id
    -   name: bil_invoices
        columns:
        -   name: invoice_date
        -   name: due_date
        -   name: total_amount
        -   name: discount_amount
        -   name: status
        -   name: created_at
        -   name: invoice_id
        -   name: customer_id
        -   name: tax_amount
        -   name: currency_code
        -   name: note
        -   name: updated_at
    -   name: mkt_campaign_targets
        columns:
        -   name: campaign_id
        -   name: assigned_date
        -   name: last_contact_date
        -   name: updated_at
        -   name: channel
        -   name: customer_id
        -   name: target_id
        -   name: response_flag
        -   name: status
        -   name: created_at
    -   name: nwk_equipment
        columns:
        -   name: model
        -   name: updated_at
        -   name: created_at
        -   name: last_maintenance_date
        -   name: status
        -   name: location
        -   name: equipment_type
        -   name: equipment_id
        -   name: assignment_id
        -   name: mac_address
        -   name: ip_address
        -   name: firmware_version
        -   name: serial_number
    -   name: sup_kb_articles
        columns:
        -   name: version_number
        -   name: external_link
        -   name: last_updated
        -   name: created_at
        -   name: updated_at
        -   name: kb_article_id
        -   name: title
        -   name: content
        -   name: category
        -   name: article_author
    -   name: bil_payments
        columns:
        -   name: transaction_id
        -   name: updated_at
        -   name: created_at
        -   name: currency_code
        -   name: payment_method
        -   name: invoice_id
        -   name: payment_date
        -   name: payment_id
        -   name: note
        -   name: amount
    -   name: crm_contacts
        columns:
        -   name: contact_value
        -   name: created_at
        -   name: is_primary
        -   name: customer_id
        -   name: updated_at
        -   name: contact_id
        -   name: note
        -   name: contact_label
        -   name: contact_type
    -   name: nwk_usage
        columns:
        -   name: usage_unit
        -   name: data_consumed
        -   name: usage_date
        -   name: assignment_id
        -   name: usage_id
        -   name: updated_at
        -   name: usage_type
        -   name: created_at
        -   name: usage_cost
        -   name: usage_peak
    -   name: bil_invoice_items
        columns:
        -   name: line_total
        -   name: updated_at
        -   name: discount_rate
        -   name: quantity
        -   name: item_code
        -   name: item_id
        -   name: invoice_id
        -   name: description
        -   name: unit_price
        -   name: tax_rate
        -   name: created_at
    -   name: mkt_campaigns
        columns:
        -   name: start_date
        -   name: target_audience
        -   name: name
        -   name: updated_at
        -   name: objective
        -   name: campaign_type
        -   name: campaign_id
        -   name: budget
        -   name: conversion_goal
        -   name: created_at
        -   name: end_date
    -   name: prv_services
        columns:
        -   name: active_flag
        -   name: description
        -   name: service_name
        -   name: service_type
        -   name: monthly_cost
        -   name: provisioning_team
        -   name: created_date
        -   name: service_id
        -   name: updated_at
    -   name: prv_service_assignments
        columns:
        -   name: start_date
        -   name: customer_id
        -   name: service_id
        -   name: provisioning_status
        -   name: last_modified_date
        -   name: assignment_id
        -   name: updated_at
        -   name: note
        -   name: created_at
        -   name: status
        -   name: end_date
    -   name: sup_ticket_notes
        columns:
        -   name: note_id
        -   name: updated_at
        -   name: ticket_id
        -   name: note_text
        -   name: created_at
        -   name: internal_flag
        -   name: note_date
        -   name: note_author
