-- This model calculates the Customer Lifetime Value (CLV)
-- CLV is defined as the average revenue generated by a customer throughout their entire relationship with the company.
-- Formula: SUM(Orders.revenue) / COUNT(DISTINCT Customers.customer_id)

with orders as (
    select *
    from {{ ref('orders') }}
),
customers as (
    select *
    from {{ ref('customers') }}
)

select
    sum(o.revenue) / count(distinct c.customer_id) as customer_lifetime_value
from orders o
join customers c
    on o.customer_id = c.customer_id
;