version: 2
sources:
  - name: raw
    tables:
    - name: sup_tickets
      columns:
      - name: customer_id
      - name: updated_at
      - name: status
      - name: ticket_id
      - name: created_date
      - name: priority
      - name: subject
      - name: description
      - name: channel_of_contact
      - name: assigned_agent
      - name: resolution_date
      - name: created_at
    - name: crm_customers
      columns:
      - name: address_line2
      - name: city
      - name: date_of_birth
      - name: state
      - name: zip_code
      - name: country
      - name: customer_segment
      - name: status
      - name: phone
      - name: email
      - name: last_name
      - name: middle_name
      - name: first_name
      - name: customer_id
      - name: note
      - name: created_at
      - name: updated_at
      - name: address_line1
      - name: customer_tier
      - name: start_date
    - name: prv_services
      columns:
      - name: provisioning_team
      - name: service_type
      - name: description
      - name: monthly_cost
      - name: active_flag
      - name: created_date
      - name: updated_at
      - name: service_name
      - name: service_id
    - name: mkt_campaign_targets
      columns:
      - name: assigned_date
      - name: target_id
      - name: campaign_id
      - name: customer_id
      - name: status
      - name: last_contact_date
      - name: channel
      - name: response_flag
      - name: created_at
      - name: updated_at
    - name: prv_service_assignments
      columns:
      - name: created_at
      - name: updated_at
      - name: assignment_id
      - name: service_id
      - name: customer_id
      - name: start_date
      - name: end_date
      - name: status
      - name: provisioning_status
      - name: last_modified_date
      - name: note
    - name: crm_opportunities
      columns:
      - name: note
      - name: account_id
      - name: stage
      - name: opportunity_id
      - name: pipeline_stage
      - name: amount
      - name: probability_of_close
      - name: close_date
      - name: assigned_sales_rep
      - name: next_step
      - name: updated_at
      - name: created_at
    - name: crm_accounts
      columns:
      - name: updated_at
      - name: account_id
      - name: customer_id
      - name: account_type
      - name: creation_date
      - name: status
      - name: currency_code
      - name: billing_address
      - name: shipping_address
      - name: account_balance
      - name: note
      - name: created_at
    - name: sup_ticket_notes
      columns:
      - name: note_id
      - name: updated_at
      - name: internal_flag
      - name: note_author
      - name: ticket_id
      - name: note_date
      - name: note_text
      - name: created_at
    - name: sup_kb_articles
      columns:
      - name: title
      - name: kb_article_id
      - name: category
      - name: article_author
      - name: updated_at
      - name: created_at
      - name: version_number
      - name: last_updated
      - name: external_link
      - name: content
    - name: nwk_outages
      columns:
      - name: resolution
      - name: outage_id
      - name: assignment_id
      - name: start_time
      - name: end_time
      - name: outage_type
      - name: region
      - name: impacted_customers_count
      - name: cause
      - name: created_at
      - name: updated_at
    - name: nwk_equipment
      columns:
      - name: last_maintenance_date
      - name: updated_at
      - name: created_at
      - name: equipment_id
      - name: assignment_id
      - name: equipment_type
      - name: model
      - name: serial_number
      - name: firmware_version
      - name: ip_address
      - name: mac_address
      - name: location
      - name: status
    - name: bil_invoice_items
      columns:
      - name: item_id
      - name: updated_at
      - name: created_at
      - name: line_total
      - name: discount_rate
      - name: tax_rate
      - name: unit_price
      - name: quantity
      - name: description
      - name: item_code
      - name: invoice_id
    - name: bil_payments
      columns:
      - name: currency_code
      - name: note
      - name: created_at
      - name: updated_at
      - name: payment_id
      - name: invoice_id
      - name: payment_date
      - name: amount
      - name: payment_method
      - name: transaction_id
    - name: mkt_campaigns
      columns:
      - name: created_at
      - name: budget
      - name: end_date
      - name: start_date
      - name: conversion_goal
      - name: target_audience
      - name: objective
      - name: campaign_type
      - name: name
      - name: campaign_id
      - name: updated_at
    - name: nwk_usage
      columns:
      - name: usage_date
      - name: usage_cost
      - name: usage_peak
      - name: usage_unit
      - name: data_consumed
      - name: usage_type
      - name: created_at
      - name: assignment_id
      - name: usage_id
      - name: updated_at
    - name: bil_invoices
      columns:
      - name: updated_at
      - name: note
      - name: status
      - name: currency_code
      - name: discount_amount
      - name: tax_amount
      - name: total_amount
      - name: due_date
      - name: invoice_date
      - name: customer_id
      - name: invoice_id
      - name: created_at
    - name: crm_contacts
      columns:
      - name: updated_at
      - name: note
      - name: contact_label
      - name: is_primary
      - name: contact_value
      - name: contact_type
      - name: customer_id
      - name: contact_id
      - name: created_at
